In [296]:
import pandas as pd

In [297]:
import warnings
warnings.filterwarnings(action='ignore')

In [298]:
import numpy as np

# 기본

In [299]:
train=pd.read_csv('re_train.csv')

In [300]:
test_data=pd.read_csv('test.csv')

In [301]:
train=train.drop('Unnamed: 0',axis=1)

In [302]:
train=pd.get_dummies(train, columns = ['gender','car','reality','income_type','edu_type','family_type','house_type','occyp_type'])

In [303]:
X=train.drop('credit',axis=1)
y =train.credit

In [304]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
X = standard_scaler.fit_transform(X)

In [305]:
from sklearn.model_selection import train_test_split
training_data, validation_data , training_labels, validation_labels = train_test_split(X, y, test_size = 0.3, random_state = 2022)
print(len(training_data))
print(len(training_labels))

print(len(validation_data))
print(len(validation_labels))

8918
8918
3822
3822


In [306]:
from imblearn.over_sampling import SMOTE
training_data, training_labels = SMOTE(random_state=0).fit_resample(training_data, training_labels)

In [307]:
training_labels.value_counts()

0    7785
1    7785
Name: credit, dtype: int64

In [308]:
from sklearn.linear_model import LogisticRegression

In [309]:
import numpy as np
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

features = training_data
target = training_labels
logistic = linear_model.LogisticRegression()
penalty = ['l1','l2'] # 페널티(penalty) 하이퍼파라미터 값의 후보를 만듭니다.
C = np.logspace(0, 4, 20) # 규제 하이퍼파라미터 값의 후보 범위를 만듭니다.
hyperparameters = dict(C=C, penalty=penalty) # 하이퍼파라미터 후보 딕셔너리를 만듭니다.


In [310]:
gridsearch = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0) # 그리드 서치 객체 생성
best_model = gridsearch.fit(features, target) # 그리드 서치 수행 

np.logspace(0, 4, 20)

array([1.00000000e+00, 1.62377674e+00, 2.63665090e+00, 4.28133240e+00,
       6.95192796e+00, 1.12883789e+01, 1.83298071e+01, 2.97635144e+01,
       4.83293024e+01, 7.84759970e+01, 1.27427499e+02, 2.06913808e+02,
       3.35981829e+02, 5.45559478e+02, 8.85866790e+02, 1.43844989e+03,
       2.33572147e+03, 3.79269019e+03, 6.15848211e+03, 1.00000000e+04])

In [311]:
# 최선의 하이퍼파라미터를 확인합니다.
print('가장 좋은 페널티:', best_model.best_estimator_.get_params()['penalty'])
print('가장 좋은 C 값:', best_model.best_estimator_.get_params()['C'])


가장 좋은 페널티: l2
가장 좋은 C 값: 1.6237767391887217


In [312]:
print(best_model.score(validation_data,validation_labels))

0.5054945054945055


In [313]:
y_pred = best_model.predict(validation_data)
y_pred

array([0, 1, 1, ..., 0, 0, 1])

In [314]:
pred=pd.DataFrame(y_pred)

In [315]:
pred.value_counts()

1    1917
0    1905
dtype: int64

# SOM

In [359]:
train=pd.read_csv('som_df.csv')

In [360]:
train=train.drop('Unnamed: 0',axis=1)

In [361]:
X=train.drop('credit',axis=1)
y =train.credit

In [362]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
X = standard_scaler.fit_transform(X)

In [363]:
from sklearn.model_selection import train_test_split
training_data, validation_data , training_labels, validation_labels = train_test_split(X, y, test_size = 0.3, random_state = 2022)
print(len(training_data))
print(len(training_labels))

print(len(validation_data))
print(len(validation_labels))

8918
8918
3822
3822


In [364]:
from imblearn.over_sampling import SMOTE
training_data, training_labels = SMOTE(random_state=0).fit_resample(training_data, training_labels)

In [365]:
training_labels.value_counts()

0    7785
1    7785
Name: credit, dtype: int64

In [366]:
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

features = training_data
target = training_labels
logistic = linear_model.LogisticRegression()
penalty = ['l1','l2'] # 페널티(penalty) 하이퍼파라미터 값의 후보를 만듭니다.
C = np.logspace(0, 4, 20) # 규제 하이퍼파라미터 값의 후보 범위를 만듭니다.
hyperparameters = dict(C=C, penalty=penalty) # 하이퍼파라미터 후보 딕셔너리를 만듭니다.

In [367]:
gridsearch = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0) # 그리드 서치 객체 생성
best_model = gridsearch.fit(features, target) # 그리드 서치 수행 

np.logspace(0, 4, 20)


array([1.00000000e+00, 1.62377674e+00, 2.63665090e+00, 4.28133240e+00,
       6.95192796e+00, 1.12883789e+01, 1.83298071e+01, 2.97635144e+01,
       4.83293024e+01, 7.84759970e+01, 1.27427499e+02, 2.06913808e+02,
       3.35981829e+02, 5.45559478e+02, 8.85866790e+02, 1.43844989e+03,
       2.33572147e+03, 3.79269019e+03, 6.15848211e+03, 1.00000000e+04])

In [368]:
# 최선의 하이퍼파라미터를 확인합니다.
print('가장 좋은 페널티:', best_model.best_estimator_.get_params()['penalty'])
print('가장 좋은 C 값:', best_model.best_estimator_.get_params()['C'])


가장 좋은 페널티: l2
가장 좋은 C 값: 545.5594781168514


In [369]:
print(best_model.score(validation_data,validation_labels))

0.4942438513867085


In [370]:
y_pred = best_model.predict(validation_data)
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [371]:
pred=pd.DataFrame(y_pred)

In [372]:
pred.value_counts()

1    1912
0    1910
dtype: int64

# Cluster

In [330]:
cluster_data=pd.read_csv('cluster.csv')

In [331]:
cluster_data=cluster_data.drop('Unnamed: 0',axis=1)

In [332]:
X=cluster_data.values
y =train.credit

In [333]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
X = standard_scaler.fit_transform(X)

In [334]:
from sklearn.model_selection import train_test_split
training_data, validation_data , training_labels, validation_labels = train_test_split(X, y, test_size = 0.3, random_state = 2022)
print(len(training_data))
print(len(training_labels))

print(len(validation_data))
print(len(validation_labels))

8918
8918
3822
3822


In [335]:
from imblearn.over_sampling import SMOTE
training_data, training_labels = SMOTE(random_state=0).fit_resample(training_data, training_labels)

In [336]:
training_labels.value_counts()

0    7785
1    7785
Name: credit, dtype: int64

In [337]:
from sklearn.linear_model import LogisticRegression

In [338]:
import numpy as np
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

features = training_data
target = training_labels
logistic = linear_model.LogisticRegression()
penalty = ['l1','l2'] # 페널티(penalty) 하이퍼파라미터 값의 후보를 만듭니다.
C = np.logspace(0, 4, 20) # 규제 하이퍼파라미터 값의 후보 범위를 만듭니다.
hyperparameters = dict(C=C, penalty=penalty) # 하이퍼파라미터 후보 딕셔너리를 만듭니다.

In [339]:
gridsearch = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0) # 그리드 서치 객체 생성
best_model = gridsearch.fit(features, target) # 그리드 서치 수행 

np.logspace(0, 4, 20)


array([1.00000000e+00, 1.62377674e+00, 2.63665090e+00, 4.28133240e+00,
       6.95192796e+00, 1.12883789e+01, 1.83298071e+01, 2.97635144e+01,
       4.83293024e+01, 7.84759970e+01, 1.27427499e+02, 2.06913808e+02,
       3.35981829e+02, 5.45559478e+02, 8.85866790e+02, 1.43844989e+03,
       2.33572147e+03, 3.79269019e+03, 6.15848211e+03, 1.00000000e+04])

In [340]:
# 최선의 하이퍼파라미터를 확인합니다.
print('가장 좋은 페널티:', best_model.best_estimator_.get_params()['penalty'])
print('가장 좋은 C 값:', best_model.best_estimator_.get_params()['C'])


가장 좋은 페널티: l2
가장 좋은 C 값: 11.28837891684689


In [341]:
print(best_model.score(validation_data,validation_labels))

0.510727367870225


In [342]:
y_pred = best_model.predict(validation_data)
y_pred

array([0, 1, 1, ..., 1, 1, 1])

In [343]:
pred=pd.DataFrame(y_pred)

In [344]:
pred.value_counts()

1    1917
0    1905
dtype: int64